# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0004_auto_20170929_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('celular', models.IntegerField(max_length=20)),
                ('cedula', models.IntegerField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
                ('labor', models.CharField(max_length=20)),
            ],
        ),
    ]
