# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0005_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='celular',
            field=models.IntegerField(),
        ),
    ]
