# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0006_auto_20171121_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='labor',
        ),
        migrations.AddField(
            model_name='empleado',
            name='ocupacion',
            field=models.CharField(choices=[('Admin de finca Finca', 'Admin de finca Finca'), ('Labores con el Cafe', 'Labores con el Cafe'), ('Labores con el Cacao', 'Labores con el Cacao')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
