# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0007_auto_20171122_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='ocupacion',
            field=models.CharField(choices=[('Admin de finca', 'Admin de finca'), ('Labores con el Cafe', 'Labores con el Cafe'), ('Labores con el Cacao', 'Labores con el Cacao')], max_length=100),
        ),
    ]
