# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0008_auto_20171122_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='empleado',
            name='municipio',
            field=models.CharField(choices=[('Pereira', 'Pereira'), ('Dosquebradas', 'Dosquebradas'), ('Santa Rosa de Cabal', 'Santa Rosa de Cabal'), ('Marsella', 'Marsella'), ('La virginia', 'La virginia')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='ocupacion',
            field=models.CharField(choices=[('Admin de finca', 'Admin de finca'), ('Labores con el café', 'Labores con el café'), ('Labores con el cacao', 'Labores con el cacao'), ('Labores con el maíz', 'Labores con el maíz'), ('Labores con el plátano', 'Labores con el plátano')], max_length=100),
        ),
    ]
