# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0009_auto_20171122_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='municipio',
            field=models.CharField(choices=[('Pereira', 'Pereira'), ('Dosquebradas', 'Dosquebradas'), ('Santa Rosa de Cabal', 'Santa Rosa de Cabal'), ('Marsella', 'Marsella'), ('La Virginia', 'La Virginia')], max_length=100),
        ),
    ]
