# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0011_auto_20171122_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_la_finca', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('municipio', models.CharField(max_length=20)),
                ('cantidad_de_dias_por_semana', models.IntegerField()),
                ('cantidad_de_horas_por_dias', models.IntegerField()),
            ],
        ),
    ]
