# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0012_cotizacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='cantidad_de_horas_por_dias',
            new_name='cantidad_de_horas_por_dia',
        ),
    ]
