# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
